### ISSUE TITLE
System dark mode issue

### ISSUE THREAD

**Issue by pxeemo** [oers/droidzebra#87]
There is bug on new Androids dark mode option everything turns white when it's enabled.

May that be fixed by this method?
https://stackoverflow.com/questions/57175226/how-to-disable-night-mode-in-my-application-even-if-night-mode-is-enable-in-andr

**Comment by oers** [comment]
I had this exact problem but then i just went away. I will look into this.
Thank you for the report.

**Comment by oers** [comment]
can you still reproduce this? I can't find a way to reproduce this on my pixel.

**Comment by pxeemo** [comment]
I think it was about MIUI force dark mode and can be turned off for any application in new versions. 
I'm now on pixel and I don't have this issue either.
Thank yor for your support.
